
services:
  app:
    container_name: employee-asset-management
    image: employee-asset-management
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres-1
  postgres-1:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres